# Generated by Django 5.2.11 on 2026-02-24 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='color_code',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Color code must be exactly 6 hexadecimal characters (example: FF5733)', regex='^[0-9A-Fa-f]{6}$')], verbose_name='Hex Color Code (without #)'),
        ),
    ]
