# Generated by Django 5.2.11 on 2026-02-24 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_service_options_service_booking_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='features',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='appointment date')),
                ('appointment_time', models.TimeField(blank=True, null=True, verbose_name='appointment time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('staff_notes', models.TextField(blank=True, verbose_name='staff notes')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('no_show', 'no show')], default='pending', max_length=20, verbose_name='status')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='total price')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='payment date')),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('cart', 'cart'), ('online', 'online'), ('wallet', 'wallet')], max_length=20, verbose_name='payment method')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='reminder sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='reminder sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.service', verbose_name='service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_staff', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['-appointment_date', 'appointment_time'],
                'indexes': [models.Index(fields=['appointment_date', 'appointment_time'], name='appointment_appoint_4c6032_idx'), models.Index(fields=['customer', 'status'], name='appointment_custome_d8b643_idx'), models.Index(fields=['staff', 'appointment_date'], name='appointment_staff_i_fa94f6_idx')],
            },
        ),
    ]
