# Generated by Django 5.2.11 on 2026-02-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='image',
        ),
    ]
