# Generated by Django 5.2.11 on 2026-02-24 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, choices=[('normal', 'normal'), ('dry', 'dry'), ('oily', 'oily'), ('sensitive', 'sensitive'), ('combination', 'combination')], default='normal', max_length=20)),
                ('hair_type', models.CharField(blank=True, choices=[('normal', 'normal'), ('wavy', 'wavy'), ('curly', 'curly'), ('coily', 'coily')], default='normal', max_length=20)),
                ('hair_color', models.CharField(blank=True, choices=[('black', 'black'), ('white', 'white'), ('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('purple', 'purple'), ('cyan', 'cyan'), ('magenta', 'magenta'), ('yellow', 'yellow'), ('cyan', 'cyan'), ('magenta', 'magenta'), ('yellow', 'yellow'), ('brown', 'brown'), ('blonde', 'blonde'), ('other', 'other')], default='black', max_length=20)),
                ('hair_length', models.CharField(blank=True, choices=[('short', 'short'), ('medium', 'medium'), ('long', 'long')], default='short', max_length=20)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='faces/%Y/%m/', verbose_name='face_image')),
                ('face_analysis_data', models.JSONField(blank=True, null=True, verbose_name='face_analysis_data')),
                ('total_reservations', models.PositiveIntegerField(default=0, verbose_name='total_reservations')),
                ('last_reservation_date', models.DateTimeField(blank=True, null=True, verbose_name='last_reservation_date')),
                ('is_vip', models.BooleanField(default=False, verbose_name='is_vip')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('wants_sms_notifications', models.BooleanField(default=False, verbose_name='wants_sms_notifications')),
                ('wants_email_notifications', models.BooleanField(default=False, verbose_name='wants_email_notifications')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'customer profile',
                'verbose_name_plural': 'customer profiles',
            },
        ),
    ]
