# Generated by Django 5.2.11 on 2026-02-24 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('user', '0003_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='experience')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff_profiles/%Y/%m/', verbose_name='profile_image')),
                ('working_hours', models.JSONField(blank=True, default=dict, null=True, verbose_name='working_hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total_reviews')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialties', models.ManyToManyField(blank=True, related_name='specialists', to='appointment.service', verbose_name='specialties')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
        ),
    ]
