# Generated by Django 5.2.11 on 2026-02-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='profile_image',
        ),
    ]
