# Generated by Django 5.2.11 on 2026-02-25 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_staffprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator(regex='^d{5} - d{5}')]),
        ),
    ]
