# Generated by Django 5.2.11 on 2026-02-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='brand')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('country', models.CharField(blank=True, choices=[('IR', 'Iran'), ('IT', 'Italy'), ('FR', 'France'), ('KR', 'South Korea'), ('TR', 'Turkey'), ('US', 'United States'), ('DE', 'Germany'), ('other', 'Other')], null=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
    ]
