# Generated by Django 5.2.11 on 2026-02-25 10:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_brand_logo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='product')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost price')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='low stock threshold')),
                ('sku', models.CharField(unique=True, validators=[django.core.validators.RegexValidator(regex='^d{5} - d{5}')])),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='barcode')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='weight')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='volume')),
                ('ingredients', models.CharField(blank=True, choices=[('Paraben_free', 'Paraben_free'), ('Sulfate_free', 'Sulfate_free'), ('Organic', 'Organic'), ('Vitamin_C', 'Vitamin_C'), ('Aloe_Vera', 'Aloe_Vera'), ('Collagen', 'Collagen'), ('Other', 'Other')], null=True, verbose_name='ingredients')),
                ('how_to_use', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('After_Bath', 'After_Bath'), ('Before_Sleep', 'Before_Sleep'), ('Other', 'Other')], null=True, verbose_name='how to use')),
                ('features', models.CharField(blank=True, choices=[('Water_Proof', 'Water_Proof'), ('Long_Lasting', 'Long_Lasting'), ('Anti_Allergy', 'Anti_Allergy'), ('fast_absorb', 'fast_absorb'), ('matter', 'matter'), ('Other', 'Other')], null=True, verbose_name='features')),
                ('suitable_for_skin', models.CharField(choices=[('all', 'all'), ('normal', 'normal'), ('dry', 'dry'), ('oily', 'oily'), ('combination', 'combination'), ('sensitive', 'sensitive')], default='all', max_length=20, verbose_name='suitable skin type')),
                ('view_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='views')),
                ('sales_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='sales')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('rating_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='rating')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=True, verbose_name='featured')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at', '-is_featured'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'), models.Index(fields=['-sales_count'], name='products_pr_sales_c_6796bf_idx')],
            },
        ),
    ]
