# Generated by Django 5.2.11 on 2026-02-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariation',
            new_name='ProductVariant',
        ),
    ]
